### ISSUE TITLE
优酷播放源播放到倒数完第二集退出后, 点击最后一集会出现"没有更新一集了"

### ISSUE THREAD

**Issue by zszen** [fuzhuo/LazyCat#4]
复现: 可复现, 退出app再进入也会产生, 播放的是优酷源的"我的英雄学院 第一季"

现象:
1.放到倒数第二集, 看完退出来
2. 点击小图标的第二个图标就是最后一集
3. 点击提示"没有更新一集了"

应该:
点击播放最后一集

临时解决方案, 直接到下面最底下列表找最后一集点击即可播放

![img_6248](https://user-images.githubusercontent.com/1890538/29700017-05135fe0-8994-11e7-850b-304618848173.JPG)

![img_6247](https://user-images.githubusercontent.com/1890538/29700025-090ee812-8994-11e7-9c3d-3984644c622e.JPG)

**Comment by fuzhuo** [comment]
已经修复，重载就好

**Comment by zszen** [comment]
![timg](https://user-images.githubusercontent.com/1890538/30004450-00bd2e6a-9102-11e7-9ab7-3d84251400de.jpg)
